export default {
    "games": "Olympic Games",
    "year": 2016,
    "season": "summer",
    "city": "Rio de Janeiro",
    "athletes": [{
            "age": 30,
            "event": "Judo Women's Middleweight",
            "gender": "F",
            "height": "176",
            "medal": "Silver",
            "name": "Yuri Alvear Orjuela",
            "noc": "COL",
            "sport": "Judo",
            "team": "Colombia",
            "weight": "70",
        },
        {
            "age": 33,
            "event": "Weightlifting Men's Featherweight",
            "gender": "M",
            "height": "159",
            "medal": "Gold",
            "name": "scar Albeyro Figueroa Mosquera",
            "noc": "COL",
            "sport": "Weightlifting",
            "team": "Colombia",
            "weight": "62",
        },
        {
            "age": 32,
            "event": "Athletics Women's Triple Jump",
            "gender": "F",
            "height": "185",
            "medal": "Gold",
            "name": "Caterine Ibargn Mena",
            "noc": "COL",
            "sport": "Athletics",
            "team": "Colombia",
            "weight": "70",
        },
        {
            "age": 24,
            "event": "Boxing Men's Light-Flyweight",
            "gender": "M",
            "height": "165",
            "medal": "Silver",
            "name": "Yurberjen Herney Martnez Rivas",
            "noc": "COL",
            "sport": "Boxing",
            "team": "Colombia",
            "weight": "49",
        },
        {
            "age": 21,
            "event": "Weightlifting Men's Lightweight",
            "gender": "M",
            "height": "165",
            "medal": "Bronze",
            "name": "Lus Javier Mosquera Lozano",
            "noc": "COL",
            "sport": "Weightlifting",
            "team": "Colombia",
            "weight": "64",
        },
        {
            "age": 24,
            "event": "Cycling Women's BMX",
            "gender": "F",
            "height": "158",
            "medal": "Gold",
            "name": "Mariana Pajn Londoo",
            "noc": "COL",
            "sport": "Cycling",
            "team": "Colombia",
            "weight": "50",
        },
        {
            "age": 22,
            "event": "Cycling Men's BMX",
            "gender": "M",
            "height": "178",
            "medal": "Bronze",
            "name": "Carlos Alberto Ramrez Yepes",
            "noc": "COL",
            "sport": "Cycling",
            "team": "Colombia",
            "weight": "65",
        },
        {
            "age": 27,
            "event": "Boxing Women's Flyweight",
            "gender": "F",
            "height": "160",
            "medal": "Bronze",
            "name": "Ingrit Lorena Valencia Victoria",
            "noc": "COL",
            "sport": "Boxing",
            "team": "Colombia",
            "weight": "50",
        },
    ],
}